export const OPEN_MODAL_ADD_DOCUMENT = 'OPEN_MODAL_ADD_DOCUMENT'
export const CLOSE_MODAL_ADD_DOCUMENT = 'CLOSE_MODAL_ADD_DOCUMENT'

export const OPEN_MODAL_FILE_ACTION = 'OPEN_MODAL_FILE_ACTION'
export const CLOSE_MODAL_FILE_ACTION = 'CLOSE_MODAL_FILE_ACTION'

export const OPEN_MODAL_FOLDER_ACTION = 'OPEN_MODAL_FOLDER_ACTION'
export const CLOSE_MODAL_FOLDER_ACTION = 'CLOSE_MODAL_FOLDER_ACTION'

export const OPEN_MODAL_CREATE_FOLDER = 'OPEN_MODAL_CREATE_FOLDER'
export const CLOSE_MODAL_CREATE_FOLDER = 'CLOSE_MODAL_CREATE_FOLDER'

export const OPEN_MODAL_ADD_FILE_INFO = 'OPEN_MODAL_ADD_FILE_INFO'
export const CLOSE_MODAL_ADD_FILE_INFO = 'CLOSE_MODAL_ADD_FILE_INFO'

export const OPEN_MODAL_ADD_GENERAL_FILE = 'OPEN_MODAL_ADD_GENERAL_FILE'
export const CLOSE_MODAL_ADD_GENERAL_FILE = 'CLOSE_MODAL_ADD_GENERAL_FILE'

export const OPEN_MODAL_TRANSFER_FOLDER = 'OPEN_MODAL_TRANSFER_FOLDER'
export const CLOSE_MODAL_TRANSFER_FOLDER = 'CLOSE_MODAL_TRANSFER_FOLDER'

export const OPEN_MODAL_FILE_SUBMIT = 'OPEN_MODAL_FILE_SUBMIT'
export const CLOSE_MODAL_FILE_SUBMIT = 'CLOSE_MODAL_FILE_SUBMIT'

export const OPEN_MODAL_SELECT_FORM = 'OPEN_MODAL_SELECT_FORM'
export const CLOSE_MODAL_SELECT_FORM = 'CLOSE_MODAL_SELECT_FORM'

export const OPEN_MODAL_SHARE_ACTION = 'OPEN_MODAL_SHARE_ACTION'
export const CLOSE_MODAL_SHARE_ACTION = 'CLOSE_MODAL_SHARE_ACTION'

export const IS_FROM_HOME = 'IS_FROM_HOME'
export const IS_NOT_FROM_HOME = 'IS_NOT_FROM_HOME'


export const OPEN_MODAL_SORT = 'OPEN_MODAL_SORT'
export const CLOSE_MODAL_SORT = 'CLOSE_MODAL_SORT'